language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

script:
  - docker-compose -f docker-compose-frpc.yml build
  - docker-compose -f docker-compose-frps.yml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alvisisme/frp:frps
  - docker push alvisisme/frp:frpc
  - docker logout
