version: '3'
services:
  frpc:
    build:
      context: .
      dockerfile: Dockerfile.frpc
      args:
        - FRP_VERSION=${FRP_VERSION}
    image: alvisisme/frp:frpc
    restart: always
    network_mode: "host"
    volumes:
      - ./frpc.ini:/etc/frpc.ini

