version: '3'
services:
  frps:
    build:
      context: .
      dockerfile: Dockerfile.frps
      args:
        - FRP_VERSION=0.41.0
    image: registry.cn-hangzhou.aliyuncs.com/alvisisme/frp:frps-0.31.2
    restart: always
    network_mode: "host"
    volumes:
      - ./frps.ini:/etc/frps.ini

