version: '3'
services:
  frpc:
    build:
      context: .
      dockerfile: Dockerfile.frpc
      args:
        - FRP_VERSION=0.31.2
    image: registry.cn-hangzhou.aliyuncs.com/alvisisme/frp:frpc-0.31.2
    restart: always
    network_mode: "host"
    volumes:
      - ./frpc.ini:/etc/frpc.ini

