version: '3'
services:
  frpc:
    build:
      context: .
      dockerfile: Dockerfile.frpc
      args:
        - FRP_VERSION=${FRP_VERSION}
    image: registry.cn-hangzhou.aliyuncs.com/alvisisme/frp:frpc-${FRP_VERSION}
    restart: always
    network_mode: "host"
    volumes:
      - ./frpc.ini:/etc/frpc.ini

