version: '3'
services:
  frps:
    build:
      context: .
      dockerfile: Dockerfile.frps
      args:
        - FRP_VERSION=${FRP_VERSION}
    image: alvisisme/frp:frps
    restart: always
    network_mode: "host"
    volumes:
      - ./frps.ini:/etc/frps.ini

