FROM alpine:3.11.3
RUN wget https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_amd64.tar.gz \
    && tar xzf frp_${FRP_VERSION}_linux_amd64.tar.gz \
    && mv frp_${FRP_VERSION}_linux_amd64/frps /usr/bin/frps \
    && mv frp_${FRP_VERSION}_linux_amd64/frps_full.ini  /etc/frps_full.ini \
    && mv frp_${FRP_VERSION}_linux_amd64/frps.ini  /etc/frps.ini \
    && rm -rf frp_${FRP_VERSION}_linux_amd64 \
    && rm -f frp_${FRP_VERSION}_linux_amd64.tar.gz \
    && frps --version
